%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/Sebas-GM/Documents/MATLAB/convolucion/Final_convolucion/data.csv
%
% Auto-generated by MATLAB on 14-Apr-2022 16:12:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["n_imp", "x_t_imp", "h_t_imp"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/Users/Sebas-GM/Documents/MATLAB/convolucion/Final_convolucion/data.csv", opts);

%% Convert to output type
n_imp = tbl.n_imp;
x_t_imp = tbl.x_t_imp;
h_t_imp = tbl.h_t_imp;

%% Clear temporary variables
clear opts tbl